sudo: required
dist: trusty
services:
- docker
before_install:
- docker build -f Dockerfile . -t richard1122/docker-shadowsocks-kcp-obfs:latest
- docker build -f Dockerfile.client . -t richard1122/docker-shadowsocks-kcp-obfs:client
script:
- docker tag richard1122/docker-shadowsocks-kcp-obfs:latest richard1122/docker-shadowsocks-kcp-obfs:server-${TRAVIS_COMMIT}
- docker tag richard1122/docker-shadowsocks-kcp-obfs:client richard1122/docker-shadowsocks-kcp-obfs:client-${TRAVIS_COMMIT}
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push richard1122/docker-shadowsocks-kcp-obfs:latest
- docker push richard1122/docker-shadowsocks-kcp-obfs:client
- docker push richard1122/docker-shadowsocks-kcp-obfs:server-${TRAVIS_COMMIT}
- docker push richard1122/docker-shadowsocks-kcp-obfs:client-${TRAVIS_COMMIT}
env:
  global:
  - secure: NRkk6EDrirQPbHYb8AWowAJlzr/SurrUoz6G46umCu4ACdPdUuLpFpFoGurhzVqdmIcDpedjMDV3we6fDErd55IG7JX1YqOf7KJ/Z1kfIP2QPghCmoY5vZ2R7wQI5krv5hseJXdVENKVFKaOXtFmjNN9sGBCSHM46NqHYDRfAnIXGXPNkvzJXVmu/OP7V03qEHbuTlKzv2CRygxNcMwvIRCiWru1NBYpOvrBSgPn0WN9GoEPVcNyKvrY9Z9p7cQ5d1Dmefa93Fn1mhZrN/D/Gl3KCtGEpKGkACCGpojxZ25XrToSMaBaWH30Rl/t4xe28OInQEI9Q4PXhW3UA4lD6WUdCZE/GM+TFjQwM3tiJl5dtKmLfQPTpa8E1Rev7IoBLa2cjSGGr+Vh8I0k7A5roYXRzuXiVf+vnnsH2HSdXB07VwfGleV/0Aim0LCYeqOpPvOeMW0ePaWJkrC1GrT7DRMLbku2J1qJ5iXx3jqbnqe3zh4mx5xJyHeDAVH3AHsiWm++8Nb65v/tBH4Wqr8lQUMFZrU/rNOhODPL6z2ZfnY/kXsq2/s94lFGhkDMcF9ogaYIrCjzU1AYrld9pAYtmWdXhrkQmNuqd0esiY3xixfe3jCvJ+R480LTzSfwD99ebVuDOd89FgUyWMOhQgcp79fkACU1sbpROLsNaBe1bBA=
  - secure: B9ThxtSD7gk501X0J25vnXDKQKuIVjgzd8n5f4MBLlRRiTDwlg60nrE3+xFabkDTAXNTJjEHj4nDtgtARkKN1L1Js8jszo7mwpeCCVxiIn4SNgdhBRa1bR056IuaA0Ww/MDnrGn2KjlWMe9qrvlvVGCSJTjSXaoU+8zuTv9mkz0XGqOPScHVlNQsa6oCfgFv5hmrGyaGXuY0di5l95UJoBkKe27m1oUQy9MyzZYacBBqCxGCfQ+6kAJVem/uPoznIrFc9ze8DJ8TLRrMFk076Bn0q+fGErSk9mV72ls0s4VS0VlSJeptX/uHLSmq4ryX38H+bCabHc51MyTj39Q7MTt0zYenLlBVogk2kZlREzDJU7IrQH9WTChgDcDYooJoGqj5iJNCf3FyXDC7stPVW2tgS0WhsMWU2CYf6EQgCp2+YK/yiZBUoWHnbXmA/uY8sa4sJ8qPAEMm30vbHb2KrUEd5rDSYs8+DqsgTiw/u72CGVYPq0KNWAS4w8wPlLjX9OX4w6Fynlotjv2BPMq0S0yVVr4uuxupF5ruMJRc/IAFQ/IMeaEgEj/D4aLTcKyMfe2wh1qM+e0/2euuVm2h3OICEmwF75HJKECpx7ZeQnFGJHzEPHPn3kMEu2UDkKidPidpi7LDQVWgvG1Lhs4Qm4pByu18gB+DvBlzSLkjWCk=
